[workspace]
resolver = "3"
members = ["crates/core", "crates/render", "crates/server"]

[workspace.package]
version = "0.2.0"
edition = "2024"
authors = ["Xevion <xevion@xevion.dev>"]
license = "MIT"
repository = "https://github.com/Xevion/time-banner"

[profile.dev-release]
inherits = "dev"
debug-assertions = false
