disallowed-macros = [
    { path = "std::assert", reason = "use assert2::assert! instead" },
    { path = "std::assert_eq", reason = "use assert2::assert!(a == b) instead" },
    { path = "std::assert_ne", reason = "use assert2::assert!(a != b) instead" },
    { path = "std::debug_assert", reason = "use assert2::debug_assert! instead" },
    { path = "std::debug_assert_eq", reason = "use assert2::debug_assert!(a == b) instead" },
    { path = "std::debug_assert_ne", reason = "use assert2::debug_assert!(a != b) instead" },
]
