#![allow(dead_code)]

use jiff::tz::Offset;

// Generated by build.rs - timezone abbreviation to UTC offset mapping
include!(concat!(env!("OUT_DIR"), "/timezone_map.rs"));

/// Parse a timezone abbreviation into a UTC offset.
///
/// This uses a pre-generated map of timezone abbreviations to their UTC offsets
/// in seconds. The mapping is based on the Wikipedia reference of timezone
/// abbreviations (as of 2023-07-20).
///
/// Note: Timezone abbreviations are not standardized and can be ambiguous.
/// This implementation uses preferred interpretations for conflicting abbreviations.
///
/// # Arguments
/// * `abbreviation` - The timezone abbreviation (e.g., "CST", "EST", "PST")
///
/// # Returns
/// * `Ok(Offset)` - The UTC offset for the timezone
/// * `Err(String)` - Error message if abbreviation is not found or invalid
pub fn parse_abbreviation(abbreviation: &str) -> Result<Offset, String> {
    let offset_seconds = TIMEZONE_OFFSETS
        .get(abbreviation)
        .ok_or_else(|| format!("Unknown timezone abbreviation: {}", abbreviation))?;

    Offset::from_seconds(*offset_seconds).map_err(|e| {
        format!(
            "Invalid offset for timezone {}: {} seconds ({})",
            abbreviation, offset_seconds, e
        )
    })
}

#[cfg(test)]
mod tests {
    use assert2::{assert, check};
    use jiff::tz::Offset;
    use rstest::rstest;

    use crate::abbr_tz::parse_abbreviation;

    #[rstest]
    #[case::cst("CST", -6 * 3600)]
    #[case::est("EST", -5 * 3600)]
    #[case::utc("UTC", 0)]
    #[case::jst_positive_offset("JST", 9 * 3600)]
    fn parses_known_abbreviation(#[case] abbreviation: &str, #[case] offset_seconds: i32) {
        let offset = parse_abbreviation(abbreviation).unwrap();
        check!(offset == Offset::from_seconds(offset_seconds).unwrap());
    }

    #[test]
    fn unknown_abbreviation_is_an_error() {
        let result = parse_abbreviation("INVALID");
        assert!(let Err(message) = result);
        assert!(message.contains("Unknown timezone abbreviation"));
    }
}
