#![allow(dead_code)]

use jiff::tz::Offset;

// Generated by build.rs - timezone abbreviation to UTC offset mapping
include!(concat!(env!("OUT_DIR"), "/timezone_map.rs"));

/// Parse a timezone abbreviation into a UTC offset.
///
/// This uses a pre-generated map of timezone abbreviations to their UTC offsets
/// in seconds. The mapping is based on the Wikipedia reference of timezone
/// abbreviations (as of 2023-07-20).
///
/// Note: Timezone abbreviations are not standardized and can be ambiguous.
/// This implementation uses preferred interpretations for conflicting abbreviations.
///
/// # Arguments
/// * `abbreviation` - The timezone abbreviation (e.g., "CST", "EST", "PST")
///
/// # Returns
/// * `Ok(Offset)` - The UTC offset for the timezone
/// * `Err(String)` - Error message if abbreviation is not found or invalid
pub fn parse_abbreviation(abbreviation: &str) -> Result<Offset, String> {
    let offset_seconds = TIMEZONE_OFFSETS
        .get(abbreviation)
        .ok_or_else(|| format!("Unknown timezone abbreviation: {}", abbreviation))?;

    Offset::from_seconds(*offset_seconds).map_err(|e| {
        format!(
            "Invalid offset for timezone {}: {} seconds ({})",
            abbreviation, offset_seconds, e
        )
    })
}

#[cfg(test)]
mod tests {
    use crate::abbr_tz::parse_abbreviation;
    use jiff::tz::Offset;

    #[test]
    fn test_parse_cst() {
        // CST (Central Standard Time) is UTC-6
        let cst = parse_abbreviation("CST").unwrap();
        assert_eq!(cst, Offset::from_seconds(-6 * 3600).unwrap());
    }

    #[test]
    fn test_parse_est() {
        // EST (Eastern Standard Time) is UTC-5
        let est = parse_abbreviation("EST").unwrap();
        assert_eq!(est, Offset::from_seconds(-5 * 3600).unwrap());
    }

    #[test]
    fn test_parse_utc() {
        // UTC should be zero offset
        let utc = parse_abbreviation("UTC").unwrap();
        assert_eq!(utc, Offset::from_seconds(0).unwrap());
    }

    #[test]
    fn test_parse_unknown() {
        // Unknown abbreviation should return error
        let result = parse_abbreviation("INVALID");
        assert!(result.is_err());
        assert!(
            result
                .unwrap_err()
                .contains("Unknown timezone abbreviation")
        );
    }

    #[test]
    fn test_parse_positive_offset() {
        // JST (Japan Standard Time) is UTC+9
        let jst = parse_abbreviation("JST").unwrap();
        assert_eq!(jst, Offset::from_seconds(9 * 3600).unwrap());
    }
}
