//! Timezone abbreviation lookup, backed by a table generated at build time
//! from `src/abbr_tz`.

/// One abbreviation's resolution: the region's IANA zone, plus the UTC offset
/// the abbreviation itself names.
///
/// The offset is not used for resolution (the zone is, so that DST is
/// followed); it is retained as the reference the table was curated against.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct TzEntry {
    pub zone: &'static str,
    pub offset_seconds: i32,
}

// Generated by build.rs - timezone abbreviation to IANA zone mapping
include!(concat!(env!("OUT_DIR"), "/timezone_map.rs"));

/// Looks up a timezone abbreviation, which must already be uppercased.
///
/// Abbreviations are not unique, so the table encodes one reading per
/// abbreviation, chosen by how the abbreviation is predominantly used in
/// English rather than by the population it covers.
pub fn lookup(abbreviation: &str) -> Option<TzEntry> {
    TIMEZONE_ABBREVIATIONS.get(abbreviation).copied()
}

#[cfg(test)]
mod tests {
    use assert2::check;
    use jiff::{Timestamp, tz::TimeZone};
    use rstest::rstest;

    use super::*;

    /// Abbreviations whose named offset no longer matches any point in their
    /// region's year, because the region changed its rules after the table's
    /// source snapshot. The zone is still the right answer for the caller;
    /// only the recorded offset is stale.
    const OFFSET_DRIFT: &[(&str, &str)] = &[
        ("ALMT", "Kazakhstan unified on +05 in March 2024"),
        ("AMST", "Brazil abolished daylight saving in 2019"),
        ("BRST", "Brazil abolished daylight saving in 2019"),
        ("CHOST", "Mongolia abolished daylight saving in 2017"),
        ("COST", "Colombia last observed daylight saving in 1993"),
        (
            "EGST",
            "Greenland shifted Scoresbysund to -02/-01 in March 2024",
        ),
        ("FKT", "the Falklands stopped changing clocks in 2011"),
        ("HOVST", "Mongolia abolished daylight saving in 2017"),
        ("IRDT", "Iran abolished daylight saving in 2022"),
        ("MAGT", "Magadan moved from +12 to +11 in 2016"),
        ("PYT", "Paraguay stopped changing clocks in October 2024"),
        ("SDT", "American Samoa does not observe daylight saving"),
        ("ULAST", "Mongolia abolished daylight saving in 2017"),
        ("UYST", "Uruguay abolished daylight saving in 2015"),
        (
            "VOST",
            "Vostok Station moved from +06 to +05 in December 2023",
        ),
        ("WGT", "Greenland shifted Nuuk to -02/-01 in March 2024"),
    ];

    /// Mid-winter and mid-summer probes, enough to see both sides of a DST
    /// transition for either hemisphere.
    fn probes() -> [Timestamp; 2] {
        [
            "2025-01-15T12:00:00Z".parse().unwrap(),
            "2025-07-15T12:00:00Z".parse().unwrap(),
        ]
    }

    #[rstest]
    #[case::cst_is_us_central("CST", "America/Chicago")]
    #[case::ist_is_india("IST", "Asia/Kolkata")]
    #[case::bst_is_britain("BST", "Europe/London")]
    #[case::jst_is_japan("JST", "Asia/Tokyo")]
    #[case::utc("UTC", "UTC")]
    fn resolves_a_known_abbreviation(#[case] abbreviation: &str, #[case] zone: &str) {
        check!(lookup(abbreviation).unwrap().zone == zone);
    }

    #[test]
    fn unknown_abbreviation_is_absent() {
        check!(lookup("INVALID") == None);
    }

    #[test]
    fn lookup_is_case_sensitive_on_purpose() {
        check!(lookup("cst") == None);
    }

    /// Every zone in the table must exist in the bundled tzdb. This is what
    /// catches a typo or a renamed identifier in the curated data file.
    #[test]
    fn every_zone_resolves() {
        let unknown: Vec<String> = TIMEZONE_ABBREVIATIONS
            .entries()
            .filter(|(_, entry)| TimeZone::get(entry.zone).is_err())
            .map(|(abbreviation, entry)| format!("{abbreviation} -> {}", entry.zone))
            .collect();

        check!(unknown.is_empty(), "unknown zones: {unknown:?}");
    }

    /// Every zone must actually observe its abbreviation's offset at some
    /// point in the year, which catches a plausible-looking zone from the
    /// wrong region or hemisphere.
    #[test]
    fn every_zone_observes_its_recorded_offset() {
        let mismatched: Vec<String> = TIMEZONE_ABBREVIATIONS
            .entries()
            .filter(|(abbreviation, _)| !OFFSET_DRIFT.iter().any(|(abbr, _)| abbr == *abbreviation))
            .filter_map(|(abbreviation, entry)| {
                let tz = TimeZone::get(entry.zone).ok()?;
                let observed = probes().map(|probe| tz.to_offset(probe).seconds());
                (!observed.contains(&entry.offset_seconds)).then(|| {
                    format!(
                        "{abbreviation} records {} but {} observes {observed:?}",
                        entry.offset_seconds, entry.zone
                    )
                })
            })
            .collect();

        check!(mismatched.is_empty(), "offset mismatches: {mismatched:#?}");
    }
}
